import { computed } from "@preact/signals";
import { toJs } from "./code";
import {
  createConfigObjectSignal,
  createFieldSignals,
  createJsonSignals,
  Fields,
  resetFieldSignals,
} from "./fields";
import { prefix } from "./persisted";
import { sdkV2Signal } from "./v2";

export function reset() {
  resetFieldSignals(fields, fieldSignals);
  jsonTextSignal.value = "{}";
}

export const playFnSignal = computed(() => {
  const sdkV2 = sdkV2Signal.value;
  const configObject = configObjectSignal.value;
  return function requestPay() {
    if (!sdkV2) return Promise.reject(new Error("sdk not loaded"));
    return sdkV2.PortOne.requestPayment(configObject);
  };
});

export const codePreviewSignal = computed<string>(() => {
  const configObject = configObjectSignal.value;
  return [
    `<script src="https://cdn.portone.io/v2/browser-sdk.js"></script>`,
    ``,
    `<button onclick="requestPay()">결제하기</button>`,
    ``,
    `<script>`,
    `function requestPay() {`,
    `  PortOne.requestPayment(${toJs(configObject, "  ", 1)});`,
    `}`,
    `</script>`,
  ].join("\n");
});

const bankCodeOptions = [
  "BANK_OF_KOREA",
  "KOREA_DEVELOPMENT_BANK",
  "INDUSTRIAL_BANK_OF_KOREA",
  "KOOKMIN_BANK",
  "SUHYUP_BANK",
  "EXPORT_IMPORT_BANK_OF_KOREA",
  "NH_NONGHYUP_BANK",
  "LOCAL_NONGHYUP",
  "WOORI_BANK",
  "SC_BANK_KOREA",
  "CITI_BANK_KOREA",
  "DAEGU_BANK",
  "BUSAN_BANK",
  "GWANGJU_BANK",
  "JEJU_BANK",
  "JEONBUK_BANK",
  "KYONGNAM_BANK",
  "KFCC",
  "SHINHYUP",
  "SAVINGS_BANK_KOREA",
  "MORGAN_STANLEY_BANK",
  "HSBC_BANK",
  "DEUTSCHE_BANK",
  "JP_MORGAN_CHASE_BANK",
  "MIZUHO_BANK",
  "MUFG_BANK",
  "BANK_OF_AMERICA_BANK",
  "BNP_PARIBAS_BANK",
  "ICBC",
  "BANK_OF_CHINA",
  "NATIONAL_FORESTRY_COOPERATIVE_FEDERATION",
  "UNITED_OVERSEAS_BANK",
  "BANK_OF_COMMUNICATIONS",
  "CHINA_CONSTRUCTION_BANK",
  "EPOST",
  "KODIT",
  "KIBO",
  "HANA_BANK",
  "SHINHAN_BANK",
  "K_BANK",
  "KAKAO_BANK",
  "TOSS_BANK",
  "KCIS",
  "DAISHIN_SAVINGS_BANK",
  "SBI_SAVINGS_BANK",
  "HK_SAVINGS_BANK",
  "WELCOME_SAVINGS_BANK",
  "SHINHAN_SAVINGS_BANK",
  "KYOBO_SECURITIES",
  "DAISHIN_SECURITIES",
  "MERITZ_SECURITIES",
  "MIRAE_ASSET_SECURITIES",
  "BOOKOOK_SECURITIES",
  "SAMSUNG_SECURITIES",
  "SHINYOUNG_SECURITIES",
  "SHINHAN_FINANCIAL_INVESTMENT",
  "YUANTA_SECURITIES",
  "EUGENE_INVESTMENT_SECURITIES",
  "KAKAO_PAY_SECURITIES",
  "TOSS_SECURITIES",
  "KOREA_FOSS_SECURITIES",
  "HANA_FINANCIAL_INVESTMENT",
  "HI_INVESTMENT_SECURITIES",
  "KOREA_INVESTMENT_SECURITIES",
  "HANWHA_INVESTMENT_SECURITIES",
  "HYUNDAI_MOTOR_SECURITIES",
  "DB_FINANCIAL_INVESTMENT",
  "KB_SECURITIES",
  "KTB_INVESTMENT_SECURITIES",
  "NH_INVESTMENT_SECURITIES",
  "SK_SECURITIES",
  "SCI",
  "KIWOOM_SECURITIES",
  "EBEST_INVESTMENT_SECURITIES",
  "CAPE_INVESTMENT_CERTIFICATE",
];

const cardCompanyOptions = [
  "KOREA_DEVELOPMENT_BANK",
  "KFCC",
  "SHINHYUP",
  "EPOST",
  "SAVINGS_BANK_KOREA",
  "KAKAO_BANK",
  "WOORI_CARD",
  "BC_CARD",
  "GWANGJU_CARD",
  "SAMSUNG_CARD",
  "SHINHAN_CARD",
  "HYUNDAI_CARD",
  "LOTTE_CARD",
  "SUHYUP_CARD",
  "CITI_CARD",
  "NH_CARD",
  "JEONBUK_CARD",
  "JEJU_CARD",
  "HANA_CARD",
  "KOOKMIN_CARD",
  "K_BANK",
  "TOSS_BANK",
  "MIRAE_ASSET_SECURITIES",
];

const carrierOptions = [
  "SKT",
  "KT",
  "LGU",
  "HELLO",
  "KCT",
  "SK7",
];

export const fields = {
  storeId: {
    required: true,
    label: "상점 ID",
    input: {
      type: "text",
      placeholder: "store-aabcdeff-0000-1234-abcd-00001234abcd",
      default: "",
    },
  },
  paymentId: {
    required: true,
    label: "결제 ID",
    input: {
      type: "text",
      default: "",
      placeholder: "",
      generate: () => `test${Date.now().toString(36)}`,
    },
  },
  orderName: {
    required: true,
    label: "주문명",
    input: {
      type: "text",
      placeholder: "짜장면 1개 단무지 추가",
      default: "",
    },
  },
  totalAmount: {
    required: true,
    label: "금액",
    input: {
      type: "integer",
      default: 0,
    },
  },
  currency: {
    required: true,
    label: "결제 통화",
    input: {
      type: "enum",
      placeholder: "KRW | USD | EUR | JPY",
      default: "",
      options: [
        "KRW",
        "USD",
        "EUR",
        "JPY",
        "CNY",
        "VND",
        "THB",
        "SGD",
        "AUD",
        "HKD",
        "AED",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BGN",
        "BHD",
        "BIF",
        "BMD",
        "BND",
        "BOB",
        "BOV",
        "BRL",
        "BSD",
        "BTN",
        "BWP",
        "BYN",
        "BZD",
        "CAD",
        "CDF",
        "CHE",
        "CHF",
        "CHW",
        "CLF",
        "CLP",
        "COP",
        "COU",
        "CRC",
        "CUC",
        "CUP",
        "CVE",
        "CZK",
        "DJF",
        "DKK",
        "DOP",
        "DZD",
        "EGP",
        "ERN",
        "ETB",
        "FJD",
        "FKP",
        "GBP",
        "GEL",
        "GHS",
        "GIP",
        "GMD",
        "GNF",
        "GTQ",
        "GYD",
        "HNL",
        "HRK",
        "HTG",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "IQD",
        "IRR",
        "ISK",
        "JMD",
        "JOD",
        "KES",
        "KGS",
        "KHR",
        "KMF",
        "KPW",
        "KWD",
        "KYD",
        "KZT",
        "LAK",
        "LBP",
        "LKR",
        "LRD",
        "LSL",
        "LYD",
        "MAD",
        "MDL",
        "MGA",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MRU",
        "MUR",
        "MVR",
        "MWK",
        "MXN",
        "MXV",
        "MZN",
        "NAD",
        "NGN",
        "NIO",
        "NOK",
        "NPR",
        "NZD",
        "OMR",
        "PAB",
        "PEN",
        "PGK",
        "PHP",
        "PKR",
        "PLN",
        "PYG",
        "QAR",
        "RON",
        "RSD",
        "RUB",
        "RWF",
        "SAR",
        "SBD",
        "SCR",
        "SDG",
        "SEK",
        "SHP",
        "SLE",
        "SLL",
        "SOS",
        "SRD",
        "SSP",
        "STN",
        "SVC",
        "SYP",
        "SZL",
        "TJS",
        "TMT",
        "TND",
        "TOP",
        "TRY",
        "TTD",
        "TWD",
        "TZS",
        "UAH",
        "UGX",
        "USN",
        "UYI",
        "UYU",
        "UYW",
        "UZS",
        "VED",
        "VES",
        "VUV",
        "WST",
        "XAF",
        "XAG",
        "XAU",
        "XBA",
        "XBB",
        "XBC",
        "XBD",
        "XCD",
        "XDR",
        "XOF",
        "XPD",
        "XPF",
        "XPT",
        "XSU",
        "XTS",
        "XUA",
        "XXX",
        "YER",
        "ZAR",
        "ZMW",
        "ZWL",
      ],
    },
  },
  channelKey: {
    required: true,
    label: "결제 채널 키",
    input: {
      type: "text",
      placeholder: "channel-key-aabcdeff-0000-1234-abcd-00001234abcd",
      default: "",
    },
  },
  productType: {
    required: false,
    label: "상품 유형",
    input: {
      type: "enum",
      placeholder: "PRODUCT_TYPE_REAL | PRODUCT_TYPE_DIGITAL",
      default: "",
      options: ["PRODUCT_TYPE_REAL", "PRODUCT_TYPE_DIGITAL"],
    },
  },
  payMethod: {
    required: true,
    label: "결제 수단",
    input: {
      type: "enum",
      placeholder: "CARD",
      default: "",
      options: [
        "CARD",
        "VIRTUAL_ACCOUNT",
        "TRANSFER",
        "MOBILE",
        "GIFT_CERTIFICATE",
        "EASY_PAY",
        "PAYPAL",
        "ALIPAY",
      ],
    },
  },
  card: {
    required: false,
    enabled: true,
    label: "카드 정보",
    hidden: computed(() =>
      fieldSignals.payMethod?.valueSignal?.value !== "CARD"
    ),
    input: {
      type: "object",
      fields: {
        cardCompany: {
          required: false,
          label: "카드사 다이렉트 호출 시 필요한 카드사 식별 값",
          input: {
            type: "enum",
            placeholder: "KOOKMIN_CARD",
            default: "",
            options: cardCompanyOptions,
          },
        },
        availableCards: {
          required: false,
          label: "일부 카드사만 노출 설정",
          input: {
            type: "array",
            inputItem: {
              type: "enum",
              placeholder: "KOOKMIN_CARD",
              default: "",
              options: cardCompanyOptions,
            },
            default: [],
          },
        },
        useFreeInterestFromMall: {
          required: false,
          label: "상점분담 무이자 활성화 여부",
          input: {
            type: "toggle",
            default: false,
          },
        },
        installment: {
          required: false,
          label: "할부 설정",
          input: {
            type: "object",
            fields: {
              freeInstallmentPlans: {
                required: false,
                label: "무이자 할부 설정",
                input: {
                  type: "array",
                  inputItem: {
                    type: "object",
                    fields: {
                      cardCompany: {
                        required: true,
                        label: "무이자 할부를 제공하는 카드사 식별 값",
                        input: {
                          type: "enum",
                          placeholder: "KOOKMIN_CARD",
                          default: "",
                          options: cardCompanyOptions,
                        },
                      },
                      months: {
                        required: true,
                        label: "무이자 할부를 제공하는 개월 수",
                        input: {
                          type: "array",
                          inputItem: {
                            type: "integer",
                            default: 0,
                          },
                          default: [],
                        },
                      },
                    },
                  },
                  default: [],
                },
              },
              monthOption: {
                required: false,
                label: "할부 개월 수 설정",
                input: {
                  type: "object",
                  fields: {
                    fixedMonth: {
                      required: false,
                      label: "고정된 할부 개월수",
                      input: {
                        type: "integer",
                        default: 0,
                      },
                    },
                    availableMonthList: {
                      required: false,
                      label: "선택 가능한 할부 개월수 리스트",
                      input: {
                        type: "array",
                        inputItem: {
                          type: "integer",
                          default: 0,
                        },
                        default: [],
                      },
                    },
                  },
                },
              },
            },
          },
        },
        useCardPoint: {
          required: false,
          label: "카드사 포인트 사용 여부",
          input: {
            type: "toggle",
            default: false,
          },
        },
        useAppCardOnly: {
          required: false,
          label: "앱 카드만 허용할지 여부",
          input: {
            type: "toggle",
            default: false,
          },
        },
      },
    },
  },
  virtualAccount: {
    required: false,
    enabled: true,
    label: "가상계좌 정보",
    hidden: computed(() =>
      fieldSignals.payMethod?.valueSignal?.value !== "VIRTUAL_ACCOUNT"
    ),
    input: {
      type: "object",
      fields: {
        cashReceiptType: {
          required: false,
          label: "현금영수증 발급 유형",
          input: {
            type: "enum",
            placeholder: "PERSONAL | CORPORATE | ANONYMOUS",
            default: "",
            options: ["PERSONAL", "CORPORATE", "ANONYMOUS"],
          },
        },
        customerIdentifier: {
          required: false,
          label: "현금영수증 발행 대상 식별 정보",
          input: {
            type: "text",
            placeholder: "",
            default: "",
          },
        },
        fixedOption: {
          required: false,
          label: "고정식 가상계좌 설정",
          input: {
            type: "object",
            fields: {
              pgAccountId: {
                required: false,
                label: "PG사에서 발급받은 가상계좌 ID",
                input: {
                  type: "text",
                  placeholder: "",
                  default: "",
                },
              },
              accountNumber: {
                required: false,
                label: "고정식으로 사용할 가상계좌 번호",
                input: {
                  type: "text",
                  placeholder: "",
                  default: "",
                },
              },
            },
          },
        },
        bankCode: {
          required: false,
          label: "가상계좌 발급 은행 코드",
          input: {
            type: "enum",
            placeholder: "BANK_OF_KOREA | KOREA_DEVELOPMENT_BANK",
            default: "",
            options: bankCodeOptions,
          },
        },
        accountExpiry: {
          required: false,
          label: "가상계좌 입금 만료기한",
          input: {
            type: "object",
            fields: {
              validHours: {
                required: false,
                label: "가상계좌 입금 유효 시간",
                input: {
                  type: "integer",
                  default: 1,
                },
              },
              dueDate: {
                required: false,
                label: "가상계좌 입금 유효 시각",
                input: {
                  type: "text",
                  placeholder: "YYYY-MM-DD HH:mm:ss",
                  default: "",
                },
              },
            },
          },
        },
      },
    },
  },
  transfer: {
    required: false,
    enabled: true,
    label: "계좌이체 정보",
    hidden: computed(() =>
      fieldSignals.payMethod?.valueSignal?.value !== "TRANSFER"
    ),
    input: {
      type: "object",
      fields: {
        cashReceiptType: {
          required: false,
          label: "현금영수증 발급 유형",
          input: {
            type: "enum",
            placeholder: "PERSONAL | CORPORATE | ANONYMOUS",
            default: "",
            options: ["PERSONAL", "CORPORATE", "ANONYMOUS"],
          },
        },
        customerIdentifier: {
          required: false,
          label: "현금영수증 발행 대상 식별 정보",
          input: {
            type: "text",
            placeholder: "",
            default: "",
          },
        },
        bankCode: {
          required: false,
          label: "계좌이체 은행 코드",
          input: {
            type: "enum",
            placeholder: "BANK_OF_KOREA | KOREA_DEVELOPMENT_BANK",
            default: "",
            options: bankCodeOptions,
          },
        },
      },
    },
  },
  mobile: {
    required: false,
    enabled: true,
    label: "휴대폰 소액결제 정보",
    hidden: computed(() =>
      fieldSignals.payMethod?.valueSignal?.value !== "MOBILE"
    ),
    input: {
      type: "object",
      fields: {
        carrier: {
          required: false,
          label: "소액결제 바로 호출을 위한 휴대폰 통신사",
          input: {
            type: "enum",
            placeholder: "SKT | KT | LGU",
            default: "",
            options: carrierOptions,
          },
        },
        availableCarriers: {
          required: false,
          label: "일부 통신사만 노출 설정",
          input: {
            type: "array",
            inputItem: {
              type: "enum",
              placeholder: "SKT | KT | LGU",
              default: "",
              options: carrierOptions,
            },
            default: [],
          },
        },
      },
    },
  },
  giftCertificate: {
    required: false,
    enabled: true,
    label: "상품권 정보",
    hidden: computed(() =>
      fieldSignals.payMethod?.valueSignal?.value !== "GIFT_CERTIFICATE"
    ),
    input: {
      type: "object",
      fields: {
        giftCertificateType: {
          required: false,
          label: "상품권 유형",
          input: {
            type: "enum",
            placeholder: "BOOKNLIFE | SMART_MUNSANG | CULTURELAND | HAPPYMONEY",
            default: "",
            options: [
              "BOOKNLIFE",
              "SMART_MUNSANG",
              "CULTURELAND",
              "HAPPYMONEY",
              "CULTURE_GIFT",
            ],
          },
        },
      },
    },
  },
  easyPay: {
    required: false,
    enabled: true,
    label: "간편결제 정보",
    hidden: computed(() =>
      fieldSignals.payMethod?.valueSignal?.value !== "EASY_PAY"
    ),
    input: {
      type: "object",
      fields: {
        easyPayProvider: {
          required: false,
          label: "간편결제 수단",
          input: {
            type: "enum",
            placeholder: "PAYCO | SAMSUNGPAY | SSGPAY | KAKAOPAY | NAVERPAY",
            default: "",
            options: [
              "PAYCO",
              "SAMSUNGPAY",
              "SSGPAY",
              "KAKAOPAY",
              "NAVERPAY",
              "CHAI",
              "LPAY",
              "KPAY",
              "TOSSPAY",
              "LGPAY",
              "APPLEPAY",
              "PINPAY",
              "SKPAY",
              "TOSS_BRANDPAY",
            ],
          },
        },
        useFreeInterestFromMall: {
          required: false,
          label: "상점분담 무이자 활성화 여부",
          input: {
            type: "toggle",
            default: false,
          },
        },
        useCardPoint: {
          required: false,
          label: "카드사 포인트 사용 여부",
          input: {
            type: "toggle",
            default: false,
          },
        },
        availableCards: {
          required: false,
          label: "일부 카드사만 노출 설정",
          input: {
            type: "array",
            inputItem: {
              type: "enum",
              placeholder: "KOOKMIN_CARD",
              default: "",
              options: cardCompanyOptions,
            },
            default: [],
          },
        },
        installment: {
          required: false,
          label: "할부 설정",
          input: {
            type: "object",
            fields: {
              freeInstallmentPlans: {
                required: false,
                label: "무이자 할부 설정",
                input: {
                  type: "array",
                  inputItem: {
                    type: "object",
                    fields: {
                      cardCompany: {
                        required: true,
                        label: "무이자 할부를 제공하는 카드사 식별 값",
                        input: {
                          type: "enum",
                          placeholder: "KOOKMIN_CARD",
                          default: "",
                          options: cardCompanyOptions,
                        },
                      },
                      months: {
                        required: true,
                        label: "무이자 할부를 제공하는 개월 수",
                        input: {
                          type: "array",
                          inputItem: {
                            type: "integer",
                            default: 0,
                          },
                          default: [],
                        },
                      },
                    },
                  },
                  default: [],
                },
              },
              monthOption: {
                required: false,
                label: "할부 개월 수 설정",
                input: {
                  type: "object",
                  fields: {
                    fixedMonth: {
                      required: false,
                      label: "고정된 할부 개월수",
                      input: {
                        type: "integer",
                        default: 0,
                      },
                    },
                    availableMonthList: {
                      required: false,
                      label: "선택 가능한 할부 개월수 리스트",
                      input: {
                        type: "array",
                        inputItem: {
                          type: "integer",
                          default: 0,
                        },
                        default: [],
                      },
                    },
                  },
                },
              },
            },
          },
        },
        cashReceiptType: {
          required: false,
          label: "현금영수증 발급 유형",
          input: {
            type: "enum",
            placeholder: "PERSONAL | CORPORATE | ANONYMOUS",
            default: "",
            options: ["PERSONAL", "CORPORATE", "ANONYMOUS"],
          },
        },
        customerIdentifier: {
          required: false,
          label: "현금영수증 발행 대상 식별 정보",
          input: {
            type: "text",
            placeholder: "",
            default: "",
          },
        },
      },
    },
  },
  customer: {
    required: false,
    label: "고객 정보",
    input: {
      type: "object",
      fields: {
        customerId: {
          required: false,
          label: "주문자 ID",
          input: {
            type: "text",
            placeholder: "",
            default: "",
            generate: () => `user_${Date.now().toString(36)}`,
          },
        },
        fullName: {
          required: false,
          label: "전체 이름",
          input: {
            type: "text",
            placeholder: "포트원",
            default: "",
          },
        },
        firstName: {
          required: false,
          label: "(성이 아닌) 이름",
          input: {
            type: "text",
            placeholder: "트원",
            default: "",
          },
        },
        lastName: {
          required: false,
          label: "성(姓)",
          input: {
            type: "text",
            placeholder: "포",
            default: "",
          },
        },
        phoneNumber: {
          required: false,
          label: "휴대폰 번호",
          input: {
            type: "text",
            placeholder: "010-1234-5678",
            default: "",
          },
        },
        email: {
          required: false,
          label: "이메일 주소",
          input: {
            type: "text",
            placeholder: "buyer@example.com",
            default: "",
          },
        },
        address: {
          required: false,
          label: "주소",
          input: {
            type: "object",
            fields: {
              country: {
                required: false,
                label: "국가",
                input: {
                  type: "enum",
                  placeholder: "KR",
                  default: "",
                  options: [
                    "AF",
                    "AX",
                    "AL",
                    "DZ",
                    "AS",
                    "AD",
                    "AO",
                    "AI",
                    "AQ",
                    "AG",
                    "AR",
                    "AM",
                    "AW",
                    "AU",
                    "AT",
                    "AZ",
                    "BH",
                    "BS",
                    "BD",
                    "BB",
                    "BY",
                    "BE",
                    "BZ",
                    "BJ",
                    "BM",
                    "BT",
                    "BO",
                    "BQ",
                    "BA",
                    "BW",
                    "BV",
                    "BR",
                    "IO",
                    "BN",
                    "BG",
                    "BF",
                    "BI",
                    "KH",
                    "CM",
                    "CA",
                    "CV",
                    "KY",
                    "CF",
                    "TD",
                    "CL",
                    "CN",
                    "CX",
                    "CC",
                    "CO",
                    "KM",
                    "CG",
                    "CD",
                    "CK",
                    "CR",
                    "CI",
                    "HR",
                    "CU",
                    "CW",
                    "CY",
                    "CZ",
                    "DK",
                    "DJ",
                    "DM",
                    "DO",
                    "EC",
                    "EG",
                    "SV",
                    "GQ",
                    "ER",
                    "EE",
                    "ET",
                    "FK",
                    "FO",
                    "FJ",
                    "FI",
                    "FR",
                    "GF",
                    "PF",
                    "TF",
                    "GA",
                    "GM",
                    "GE",
                    "DE",
                    "GH",
                    "GI",
                    "GR",
                    "GL",
                    "GD",
                    "GP",
                    "GU",
                    "GT",
                    "GG",
                    "GN",
                    "GW",
                    "GY",
                    "HT",
                    "HM",
                    "VA",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IN",
                    "ID",
                    "IR",
                    "IQ",
                    "IE",
                    "IM",
                    "IL",
                    "IT",
                    "JM",
                    "JP",
                    "JE",
                    "JO",
                    "KZ",
                    "KE",
                    "KI",
                    "KP",
                    "KR",
                    "KW",
                    "KG",
                    "LA",
                    "LV",
                    "LB",
                    "LS",
                    "LR",
                    "LY",
                    "LI",
                    "LT",
                    "LU",
                    "MO",
                    "MK",
                    "MG",
                    "MW",
                    "MY",
                    "MV",
                    "ML",
                    "MT",
                    "MH",
                    "MQ",
                    "MR",
                    "MU",
                    "YT",
                    "MX",
                    "FM",
                    "MD",
                    "MC",
                    "MN",
                    "ME",
                    "MS",
                    "MA",
                    "MZ",
                    "MM",
                    "NA",
                    "NR",
                    "NP",
                    "NL",
                    "NC",
                    "NZ",
                    "NI",
                    "NE",
                    "NG",
                    "NU",
                    "NF",
                    "MP",
                    "NO",
                    "OM",
                    "PK",
                    "PW",
                    "PS",
                    "PA",
                    "PG",
                    "PY",
                    "PE",
                    "PH",
                    "PN",
                    "PL",
                    "PT",
                    "PR",
                    "QA",
                    "RE",
                    "RO",
                    "RU",
                    "RW",
                    "BL",
                    "SH",
                    "KN",
                    "LC",
                    "MF",
                    "PM",
                    "VC",
                    "WS",
                    "SM",
                    "ST",
                    "SA",
                    "SN",
                    "RS",
                    "SC",
                    "SL",
                    "SG",
                    "SX",
                    "SK",
                    "SI",
                    "SB",
                    "SO",
                    "ZA",
                    "GS",
                    "SS",
                    "ES",
                    "LK",
                    "SD",
                    "SR",
                    "SJ",
                    "SZ",
                    "SE",
                    "CH",
                    "SY",
                    "TW",
                    "TJ",
                    "TZ",
                    "TH",
                    "TL",
                    "TG",
                    "TK",
                    "TO",
                    "TT",
                    "TN",
                    "TR",
                    "TM",
                    "TC",
                    "TV",
                    "UG",
                    "UA",
                    "AE",
                    "GB",
                    "US",
                    "UM",
                    "UY",
                    "UZ",
                    "VU",
                    "VE",
                    "VN",
                    "VG",
                    "VI",
                    "WF",
                    "EH",
                    "YE",
                    "ZM",
                    "ZW",
                  ],
                },
              },
              addressLine1: {
                required: false,
                label: "일반 주소",
                input: {
                  type: "text",
                  placeholder: "성수이로20길 16",
                  default: "",
                },
              },
              addressLine2: {
                required: false,
                label: "상세 주소",
                input: {
                  type: "text",
                  placeholder: "제이케이타워 4층",
                  default: "",
                },
              },
              city: {
                required: false,
                label: "도시",
                input: {
                  type: "text",
                  placeholder: "성동구",
                  default: "",
                },
              },
              province: {
                required: false,
                label: "주, 도, 시",
                input: {
                  type: "text",
                  placeholder: "서울특별시",
                  default: "",
                },
              },
            },
          },
        },
        zipcode: {
          required: false,
          label: "우편번호",
          input: {
            type: "text",
            placeholder: "01234",
            default: "",
          },
        },
        gender: {
          required: false,
          label: "구매자 성별",
          input: {
            type: "enum",
            placeholder: "OTHER",
            default: "",
            options: [
              "MALE",
              "FEMALE",
              "OTHER",
            ],
          },
        },
        birthYear: {
          required: false,
          label: "출생년도",
          input: {
            type: "text",
            placeholder: "1970",
            default: "",
          },
        },
        birthMonth: {
          required: false,
          label: "출생월",
          input: {
            type: "text",
            placeholder: "1",
            default: "",
          },
        },
        birthDay: {
          required: false,
          label: "출생일",
          input: {
            type: "text",
            placeholder: "1",
            default: "",
          },
        },
      },
    },
  },
  windowType: {
    required: false,
    label: "결제 창 유형",
    input: {
      type: "object",
      fields: {
        pc: {
          required: false,
          label: "PC에서의 창 유형",
          input: {
            type: "enum",
            placeholder: "IFRAME",
            default: "",
            options: [
              "IFRAME",
              "POPUP",
              "REDIRECTION",
              "UI",
            ],
          },
        },
        mobile: {
          required: false,
          label: "모바일에서의 창 유형",
          input: {
            type: "enum",
            placeholder: "REDIRECTION",
            default: "",
            options: [
              "IFRAME",
              "POPUP",
              "REDIRECTION",
              "UI",
            ],
          },
        },
      },
    },
  },
  redirectUrl: {
    required: false,
    label: "결제 후 이동할 URL",
    input: {
      type: "text",
      placeholder: "https://example.com",
      default: "",
    },
  },
  noticeUrls: {
    required: false,
    label: "웹훅 수신 URL",
    input: {
      type: "array",
      inputItem: {
        type: "text",
        default: "",
        placeholder: "https://example.com",
      },
      default: [],
    },
  },
} satisfies Fields;

export const fieldSignals = createFieldSignals(
  localStorage,
  `${prefix}.v2-pay.fields`,
  fields,
);
export const { jsonTextSignal, jsonValueSignal } = createJsonSignals(
  localStorage,
  `${prefix}.v2-pay.json`,
);
export const configObjectSignal = createConfigObjectSignal({
  fields,
  fieldSignals,
  jsonValueSignal,
});
